version: 2.1
jobs:
  plan: &plan
    executor: terraform-executor
    steps:
      - checkout
      - install-notifier
      - run:
          name: terraform plan
          command: |
            #TODO: share.auto.tfvars
            case "$TF_WORKSPACE" in
              common)
                export TF_WORKSPACE=default
                cd common
                terraform init -input=false
                terraform workspace list
                terraform plan -input=false 2>&1 | tee /tmp/plan.log
                ;;
              *)
                terraform init -input=false
                terraform workspace list
                terraform plan -input=false 2>&1 | tee /tmp/plan.log
                ;;
            esac
      - run:
          name: tfnotify plan
          command: |
            #cat /tmp/plan.log | tfnotify plan --message "$TF_WORKSPACE"
      - persist_to_workspace:
          root: ~/project
          paths:
            -  common/.terraform
            -  .terraform
            -  tfnotify

  plan-common:
    <<: *plan
    environment:
      TF_WORKSPACE: common
  plan-staging:
    <<: *plan
    environment:
      TF_WORKSPACE: staging 
  plan-production:
    <<: *plan
    environment:
      TF_WORKSPACE: production

  apply:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: terraform apply
          command: |
            #terraform apply -input=false -lock=true -auto-approve 2>&1 | tee /tmp/apply.log
            echo "applying..."
          no_output_timeout: 60m
      - run:
          name: tfnotify apply
          command: |
            #cat /tmp/apply.log | tfnotify apply --message "$TF_WORKSPACE"
  hold:
    executor: terraform-executor
    steps:
      - notify-approval

executors:
  terraform-executor:
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    docker:
      - image: hashicorp/terraform:0.11.10
        environment:
          TFNOTIFY_URL: https://github.com/mercari/tfnotify/releases/download/v0.3.0/tfnotify_v0.3.0_linux_amd64.tar.gz


commands:
  install-notifier:
    steps:
      - restore_cache:
          keys:
          - v1-{{ checksum ".circleci/config.yml" }}
          - v1-
      - run:
          name: install dependencies
          command: |
            wget $TFNOTIFY_URL  -O /tmp/t.tgz
            tar xvfz /tmp/t.tgz -C /tmp/
            mv /tmp/tfnotify*/tfnotify ~/project/
      - save_cache:
          paths:
            - ./tfnotify
          key: v1-{{ checksum ".circleci/config.yml" }}
  notify-approval:
    steps:
      - run:
          name: send notification to slack
          command: |
            curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"Please approve workflow from <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|here>.\"}" $SLACK_WEBHOOK_URL

workflows:
  version: 2
  plan-and-apply:
    jobs:
      - plan-common
      - plan-staging:
          requires:
            - plan-common
      - hold:
          requires:
            - plan-staging
      - plan-production:
          type: approval
          requires:
            - hold
#      - apply:
#          requires:
#          filters:
#            branches:
#              only:
#                - master
